- hosts: all
  vars:
    no_proxy: '127.0.0.1,localhost,.local,169.254.169.254'
  connection: local
  tasks:
    - name: execute | hosts
      set_fact:
        myget_args: '{{ hostvars[inventory_hostname] }}'
    - name: Proxy Defined
      debug:
        msg: '{{ myget_args }}'

    - name: Main
      block:
        - name: main | execute | run things
          debug:
            msg: '{{ myget_args }}'

        - name: Create Temp Dir
          tempfile:
            state: directory
            suffix: build
          register: work_dir

      always:
        - name: main | always | remove temporary working directory
          file:
            path  : "{{ work_dir.path }}"
            state : absent

        - name: notify slack of deploy failure
          debug:
            msg: "{{ work_dir.path }}"

        - name: Local Action Test
          local_action:
            module: command
            args: ping -c 1 www.google.com

        - name: Delegate to Test
          command: ping -c 1 www.google.com
          delegate_to: localhost

      rescue:
        - name: notify slack of deploy failure
          debug:
            msg: "{{ work_dir }}"
